### ISSUE TITLE
migrate from tfswitch to tenv

### ISSUE THREAD

**Issue by kvendingoldo** [cbertoldi/dotfiles#1]
Hi! I saw that you're using tfswitch. It does not support Terragrunt and OpenTofu, so, I suggest you to switch to tool that can manage all of these tools together: https://github.com/tofuutils/tenv

**Comment by cbertoldi** [comment]
Hey Alexander, thanks for letting me know. I will give it a look in case I'll have to deal with Terragrunt or OpenTofu.
